---
controller_projects:
  - name: ""
    description: "Generated bootstrap playbooks"
    organization: ""
    scm_type: git
    scm_url: "https://github.com/LoganCorderRedHat/ado-openshift-tests.git"
    scm_branch: "main"
    scm_update_on_launch: true
    scm_update_cache_timeout: 0
    scm_clean: true
    scm_credential: >-
      ocp-gitlab
    wait: true
